version: "2"
services:
  elasticsearch:
    image: docker.io/bitnami/elasticsearch:7
    volumes:
      - ./data/elastic:/bitnami/elasticsearch/data
    ports:
      - "9200:9200"
  kibana:
    image: docker.io/bitnami/kibana:7
    ports:
      - "5601:5601"
    volumes:
      - "kibana_data:/bitnami/kibana"
    depends_on:
      - elasticsearch
volumes:
  elasticsearch_data:
    driver: local
  kibana_data:
    driver: local
